on:
  push:
    branches:
      - main
name: CI & CD
jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Get Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.
      - name: Testing App
        run: |
          npm install
          npm run test
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2
      - name: Get Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.
      - name: Build
        run: |
          npm install
          npm run build